# Generated by Django 6.0.4 on 2026-04-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowlegdeCategory',
            new_name='KnowledgeCategory',
        ),
    ]
