# Generated by Django 6.0.4 on 2026-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('discovery', 'discovery'), ('quoted', 'quoted'), ('negotiation', 'negotiation'), ('closed', 'closed')], default='new', max_length=20),
        ),
    ]
