# Generated by Django 6.0.4 on 2026-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='activity_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('note_added', 'Note Added'), ('discovery_updated', 'Discovery Updated')], max_length=50),
        ),
    ]
