# Generated by Django 6.0.4 on 2026-04-21 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_tag_lead_rating_lead_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='activity_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('note_added', 'Note Added'), ('discovery_updated', 'Discovery Updated'), ('document_uploaded', 'Document Uploaded')], max_length=50),
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lead.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Document',
                'verbose_name_plural': 'Lead Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
