# Generated by Django 6.0.4 on 2026-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='activity_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('note_added', 'Note Added'), ('discovery_updated', 'Discovery Updated'), ('document_uploaded', 'Document Uploaded'), ('email_sent', 'Email Sent')], max_length=50),
        ),
    ]
