# Generated by Django 6.0.4 on 2026-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_activitytimeline_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField(default=dict, help_text='JSON representation of filter parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filter Preset',
                'verbose_name_plural': 'Filter Presets',
                'ordering': ['-created_at'],
            },
        ),
    ]
