# Generated by Django 5.1.7 on 2026-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_filterpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('not_interested', 'not_interested'), ('discovery', 'discovery'), ('quoted', 'quoted'), ('negotiation', 'negotiation'), ('closed', 'closed')], default='new', max_length=20),
        ),
    ]
