# Generated by Django 6.0.4 on 2026-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the lead', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI summary was last generated', null=True),
        ),
    ]
