# Generated by Django 6.0.4 on 2026-04-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0003_alter_activitytimeline_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discovery Category',
                'verbose_name_plural': 'Discovery Categories',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discovery.discoverycategory')),
            ],
            options={
                'verbose_name': 'Discovery Question',
                'verbose_name_plural': 'Discovery Questions',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='discovery.discoveryquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LeadDiscoveryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_answers', to='lead.lead')),
                ('options', models.ManyToManyField(related_name='lead_selections', to='discovery.discoveryoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_answers', to='discovery.discoveryquestion')),
            ],
            options={
                'verbose_name': 'Lead Discovery Answer',
                'verbose_name_plural': 'Lead Discovery Answers',
                'unique_together': {('lead', 'question')},
            },
        ),
    ]
