# Generated by Django 6.0.4 on 2026-04-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_discoveryoption_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryquestion',
            name='category',
        ),
        migrations.AddField(
            model_name='leaddiscoveryanswer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='discovery.discoverycategory'),
        ),
    ]
