# Generated by Django 6.0.4 on 2026-04-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_remove_discoveryquestion_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddiscoveryanswer',
            name='category',
        ),
        migrations.AddField(
            model_name='discoveryoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='discovery.discoverycategory'),
        ),
    ]
