# Generated by Django 6.0.4 on 2026-04-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_remove_leaddiscoveryanswer_category_and_more'),
        ('lead', '0005_alter_activitytimeline_activity_type_leaddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the stage appears')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='discoveryoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discoveryoption',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='leaddiscoveryanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leaddiscoveryanswer',
            name='options',
        ),
        migrations.RemoveField(
            model_name='leaddiscoveryanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='leaddiscoveryanswer',
            name='lead',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text for the checkbox or option')),
                ('description', models.TextField(blank=True, help_text='Additional context for this specific option')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='discovery.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The main question text')),
                ('description', models.TextField(blank=True, help_text='Subtext or instructions for the salesperson')),
                ('question_type', models.CharField(choices=[('checklist', 'Checklist (Multiple Selection)'), ('single', 'Single Choice'), ('text', 'Free Text')], default='checklist', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='discovery.category')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='discovery.salesstage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, help_text='For free-text question types', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lead.lead')),
                ('selected_answers', models.ManyToManyField(blank=True, to='discovery.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='discovery.question'),
        ),
        migrations.CreateModel(
            name='LeadStageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_problems', models.TextField(help_text='Identified problems or pain points')),
                ('recommended_approach', models.TextField(help_text='Suggested strategy to pitch Nepdora')),
                ('raw_ai_response', models.JSONField(blank=True, help_text='Full JSON response from Gemini', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='lead.lead')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.salesstage')),
            ],
            options={
                'verbose_name_plural': 'Lead Stage Analyses',
                'unique_together': {('lead', 'stage')},
            },
        ),
        migrations.DeleteModel(
            name='DiscoveryCategory',
        ),
        migrations.DeleteModel(
            name='DiscoveryOption',
        ),
        migrations.DeleteModel(
            name='DiscoveryQuestion',
        ),
        migrations.DeleteModel(
            name='LeadDiscoveryAnswer',
        ),
    ]
