# Generated by Django 6.0.4 on 2026-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_from_vat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_vat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
