# Generated by Django 6.0.4 on 2026-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_bill_from_vat_invoice_bill_to_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Received', 'Received'), ('Overdue', 'Overdue')], max_length=10, null=True),
        ),
    ]
